version: '3'
services:
  consul:
    image: 'hashicorp/consul'
    ports:
      - 8500:8500
  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demoproto
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
  nats:
    image: "nats:latest"
    ports:
      - 4444:4222
      - 8222:8222
